### ISSUE TITLE
"debug" package isn't specified as a dependency

### ISSUE THREAD

**Issue by lesha1201** [jhs67/usocket#10]
"debug" package isn't specified in `package.json` and because of that, this library can't work where this package isn't installed or when bundling it, e.g. via Webpack

![image](https://user-images.githubusercontent.com/10157660/136378208-99e88bf5-3464-4a69-aaeb-0a5a66043a3b.png)

**Comment by jhs67** [comment]
I have finally published v1.0.1 with a fix for this issue. Sorry for the extensive delay.
