### ISSUE TITLE
Write operation fails if amount of data is too large

### ISSUE THREAD

**Issue by Umdrahschua** [jhs67/usocket#11]
Hi!

I had an issue and did some research. At the end I came up that the issue is on USocket.

On my system following update to the test is working:

```
        // test/socket.js line 90
	it("can send data from server to client", function(done) {
		done = hookErrors(done);

		const str = "A".repeat(219264)
		var send = Buffer.from(str), handle;
```

But if I increase str by 1, then the test fails with a strange error. The code looks like following:

```
        // test/socket.js line 90
	it("can send data from server to client", function(done) {
		done = hookErrors(done);

		const str = "A".repeat(219265)
		var send = Buffer.from(str), handle;
```

Could it be possible that there is a bug if the amount of data exceeds a specific size of?

**Comment by Umdrahschua** [comment]
I used for the test above Alma Linux. On my macOS system the limit is different. There it is 8192. This number returns `sendmsg()`. It does not return an -1, it returns a wrong size or not all data was send.

**Comment by jhs67** [comment]
The underlying limit seems to be coming from the operating system, rather than a bug in usocket. The documentation for sendmsg does mention there is a limit for sockets in datagram mode. If this is true I'm not sure there is anything usocket could (or should) do about this. What do you think?

**Comment by Umdrahschua** [comment]
Not sure where the issue is. I would expect that `sendmsg()` blocks or an error would be returned. But it looks like this would not happen. I try to code a simple sendmsg/recvmsg example to checkout the behaviour of sending of too long messages (over uds).

I think this is not good if there is no guarantee that the `socket.write()` operation sends all data or not. At least there should be an error that the write-operation failed.

**Comment by jhs67** [comment]
What happens when you try to write over large data? According to the linux manpages for sendmsg, the error EMSGSIZE should be returned, and it looks like usocket does pass this value back to the caller. Internally usocket uses the node.js Stream module to handle buffering, so I'm not exactly sure what happens to the error, but I would expect and 'error' event to be emitted.

**Comment by Umdrahschua** [comment]
I observed this issue in [dbus-next](https://github.com/dbusjs/node-dbus-next). To find out what goes wrong I added some console.log messages to the stream events 'end', 'error' and 'drain'. But no console.log was called.

In one case dbus-next uses the Node Socket instead of USocket. I patched the installed dbus-next Node module to not use USocket and then I did not run into this issue. So I came across that the issue is in USocket (or USocket is not used correctly).

I have not seen any error messages yet. If I update this test here then the test fails differently wrong 🤷‍♂️.

**Comment by jhs67** [comment]
I looked into this and the socket is in stream mode, not datagram mode, so there shouldn't be a limit on the send size. I'll try to get a fix soon.

**Comment by Umdrahschua** [comment]
I have tested a little more. First I wrote a simple C/CPP receive code and write code (with sendmsg inspired by USocket). Writing a buffer of size 1234567890 was very fast and without issues.

Then I tried to compare my example code and USocket. My example code is blocking while USocket is not blocking. Okay, I think I understand the issue. The output buffer is full, USocket has to send the rest of the data when the output buffer is ready again.

**Comment by Umdrahschua** [comment]
Thanks 🙏. Looks good from my site. I have tested it with some old example code and with the old version and it fails, but if I use the version 1.0.1 it looks good 👍

**Comment by jhs67** [comment]
There is a queue, but it is inside the node.js `stream.Duplex` class. That class will queue up writes until all previous writes have finished. If you look near line 74 of index.js this is when the writing gets blocked because I don't call 'callback' - which is what lets the stream class know the write is finished. When the socket gets unblocked it sends an event (line 501 of uwrap.cc) and that will finish the last write (line 150 of index.js) and let the queued writes start flowing.
