### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DineshDevaraj** [jhs67/usocket#6]
root@79a311055210:~/programs/nodejs# npm install usocket

> usocket@0.2.1 install /root/programs/nodejs/node_modules/usocket
> node-gyp rebuild

sh: 1: node-gyp: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/root/programs/nodejs/package.json'
npm WARN nodejs No description
npm WARN nodejs No repository field.
npm WARN nodejs No README data
npm WARN nodejs No license field.

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! usocket@0.2.1 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the usocket@0.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-01T07_07_02_070Z-debug.log
root@79a311055210:~/programs/nodejs#

**Comment by jhs67** [comment]
It looks like node-gyp failed to find the system shell program
```
npm ERR! file sh
npm ERR! errno ENOENT
```
Maybe a problem with your PATH variable or your system install?
